package com.ninfinity.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="dbo", name="test")
public class Test {
	@Basic
	@Column(length=256)
	private String displayname;

	@Id
	@Column(columnDefinition="serial")
	private int id;

	@Basic
	private boolean isactive;

	@Basic
	@Column(length=256)
	private String name;

	@Basic
	@Column(columnDefinition="int4")
	private int startdate;


	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public String getDisplayname() {
		return displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStartdate() {
		return startdate;
	}

	public void setStartdate(int startdate) {
		this.startdate = startdate;
	}
}