package com.nfin;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="blog", name="blog")
public class Blog {
	@Id
	@Column(name="blog_id", columnDefinition="bigserial")
	private long blogId;

	@OneToMany(targetEntity=com.nfin.testemaa.domain.model.Temp.Entry.class, mappedBy="blog", cascade=CascadeType.MERGE)
	private Set entrys = new HashSet();

	@Basic
	@Column(nullable=false)
	private String handle;

	@Basic
	@Column(nullable=false)
	private String name;

	@OneToMany(targetEntity=com.nfin.testemaa.domain.model.Temp.Subscription.class, mappedBy="blog", cascade=CascadeType.MERGE)
	private Set subscriptions = new HashSet();

	@Basic
	@Column(columnDefinition="int2")
	private short tes;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="creator_id", columnDefinition="int8")
	private User user;


	public Blog() {
	}

	public Blog(long blogId) {
		this.blogId = blogId;
	}

	public long getBlogId() {
		return blogId;
	}

	public void setBlogId(long blogId) {
		this.blogId = blogId;
	}

	public Set getEntrys() {
		return entrys;
	}

	public void setEntrys(Set entrys) {
		this.entrys = entrys;
	}

	public String getHandle() {
		return handle;
	}

	public void setHandle(String handle) {
		this.handle = handle;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSubscriptions() {
		return subscriptions;
	}

	public void setSubscriptions(Set subscriptions) {
		this.subscriptions = subscriptions;
	}

	public short getTes() {
		return tes;
	}

	public void setTes(short tes) {
		this.tes = tes;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}