package com.nfin.testemaa.domain.model.Temp;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="blog", name="entry")
public class Entry {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="blog_id", columnDefinition="int8")
	private Blog blog;

	@Basic
	@Column(nullable=false)
	private String content;

	@Basic
	@Column(nullable=false)
	private Date date;

	@Id
	@Column(name="entry_id", columnDefinition="bigserial")
	private long entryId;

	@OneToMany(targetEntity=com.nfin.testemaa.domain.model.Temp.EntryTag.class, mappedBy="entry", cascade=CascadeType.MERGE)
	private Set entryTags = new HashSet();

	@Basic
	@Column(nullable=false)
	private String title;


	public Entry() {
	}

	public Entry(long entryId) {
		this.entryId = entryId;
	}

	public Blog getBlog() {
		return blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public long getEntryId() {
		return entryId;
	}

	public void setEntryId(long entryId) {
		this.entryId = entryId;
	}

	public Set getEntryTags() {
		return entryTags;
	}

	public void setEntryTags(Set entryTags) {
		this.entryTags = entryTags;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}