package com.nfin.testemaa.domain.model.Temp;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: com.nfin.testemaa.domain.model.Temp.EntryTag
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EntryTagId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("com.nfin.testemaa.domain.model.Temp.EntryTag"); }
		catch(Exception e) {}
	}

	public long entryId;
	public long tagId;

	public EntryTagId() {
	}

	public EntryTagId(String str) {
		fromString(str);
	}

	public long getEntryId() {
		return entryId;
	}

	public void setEntryId(long entryId) {
		this.entryId = entryId;
	}

	public long getTagId() {
		return tagId;
	}

	public void setTagId(long tagId) {
		this.tagId = tagId;
	}

	public String toString() {
		return String.valueOf(entryId)
			+ "::" + String.valueOf(tagId);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + (int) (entryId ^ (entryId >>> 32));
		rs = rs * 37 + (int) (tagId ^ (tagId >>> 32));
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		EntryTagId other = (EntryTagId) obj;
		return (entryId == other.entryId)
			&& (tagId == other.tagId);
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		entryId = Long.parseLong(str);
		str = toke.nextToken();
		tagId = Long.parseLong(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}