package com.nfin.testemaa.domain.model.Temp;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="blog", name="entry_tag")
@IdClass(com.nfin.testemaa.domain.model.Temp.EntryTagId.class)
public class EntryTag {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="entry_id", columnDefinition="int8")
	private Entry entry;

	@Id
	@Column(name="entry_id", columnDefinition="int8")
	private long entryId;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="tag_id", columnDefinition="int8")
	private Tag tag;

	@Id
	@Column(name="tag_id", columnDefinition="int8")
	private long tagId;


	public EntryTag() {
	}

	public EntryTag(long entryId, long tagId) {
		this.entryId = entryId;
		this.tagId = tagId;
	}

	public Entry getEntry() {
		return entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}

	public long getEntryId() {
		return entryId;
	}

	public void setEntryId(long entryId) {
		this.entryId = entryId;
	}

	public Tag getTag() {
		return tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	public long getTagId() {
		return tagId;
	}

	public void setTagId(long tagId) {
		this.tagId = tagId;
	}
}