package com.nfin.testemaa.domain.model.Temp;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: com.nfin.testemaa.domain.model.Temp.Subscription
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class SubscriptionId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("com.nfin.testemaa.domain.model.Temp.Subscription"); }
		catch(Exception e) {}
	}

	public long blogId;
	public long userId;

	public SubscriptionId() {
	}

	public SubscriptionId(String str) {
		fromString(str);
	}

	public long getBlogId() {
		return blogId;
	}

	public void setBlogId(long blogId) {
		this.blogId = blogId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String toString() {
		return String.valueOf(blogId)
			+ "::" + String.valueOf(userId);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + (int) (blogId ^ (blogId >>> 32));
		rs = rs * 37 + (int) (userId ^ (userId >>> 32));
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		SubscriptionId other = (SubscriptionId) obj;
		return (blogId == other.blogId)
			&& (userId == other.userId);
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		blogId = Long.parseLong(str);
		str = toke.nextToken();
		userId = Long.parseLong(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}